require 'rubygems'
gem 'mocha'
gem 'actionpack'
require 'actionpack'
require 'action_controller'
require 'action_controller/test_process'
require 'test/unit'
require File.dirname(__FILE__) + '/../lib/permission_check'
require 'mocha'

